package mtgx;

typedef Card = {
  id : String,
  layout : String,
  name : String,
  ?names : Array<String>,
  manaCost : String,
  cmc : Float,
  colors : Array<String>,
  colorIdentity : Array<String>,
  type : String,
  supertypes : Array<String>,
  types : Array<String>,
  subtypes : Array<String>,
  rarity : String,
  text : String,
  flavor : String,
  artist : String,
  number : String,
  power : String,
  toughness : String,
  loyalty : Int,
  multiverseid : Int,
  variations : Array<Int>,
  imageName : String,
  watermark : String,
  border : String,
  timeshifted : Bool,
  hand : Int,
  life : Int,
  reserved : Bool,
  releaseDate : String,
  starter : Bool
}
